export const DataPersonage = [
    {
        id: 1,
        rickImage: "1.png",
        mortyImage: "1.jpg",
        dimensionsId: 1,
        rickName: "Rick Sanches",
        mortyName: "Morty",
    },
    {
        id: 2,
        rickImage: "1.png",
        mortyImage: "1.jpg",
        dimensionsId: 2,
        rickName: "Rick Sanches",
        mortyName: "Morty",
    },
    {
        id: 3,
        rickImage: "1.png",
        mortyImage: "1.jpg",
        dimensionsId: 3,
        rickName: "Rick Sanches",
        mortyName: "Morty",
    },
    {
        id: 4,
        rickImage: "1.png",
        mortyImage: "1.jpg",
        dimensionsId: 5,
        rickName: "Rick Sanches",
        mortyName: "Morty",
    },
    {
        id: 6,
        rickImage: "1.png",
        mortyImage: "1.jpg",
        dimensionsId: 6,
        rickName: "Rick Sanches",
        mortyName: "Morty",
    },
    {
        id: 7,
        rickImage: "1.png",
        mortyImage: "1.jpg",
        dimensionsId: 7,
        rickName: "Rick Sanches",
        mortyName: "Morty",
    },
    {
        id: 8,
        rickImage: "1.png",
        mortyImage: "1.jpg",
        dimensionsId: 8,
        rickName: "Rick Sanches",
        mortyName: "Morty",
    },
];
